### ISSUE TITLE
Installing environment for prettier cause error.

### ISSUE THREAD

**Issue by damianbrzoza** [PiotrJZielinski/python-project-template#1]
Hi Piotrek!

There are some troubles caused by changes in prettier repository.

Possible solution:
https://github.com/prettier/prettier/issues/9459

You should change these lines in _.pre-commit-config.yaml:_

```
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
```
To something like this:

```
  -  repo: https://github.com/prettier/pre-commit
     rev: v2.1.2
```

**Comment by piotlinski** [comment]
Oh yes, they have recently changed that. I created a PR to fix this problem
